spring:
  datasource:
    name: dockerdb
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5442}/dockerdb
    username: person
    password: person
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
